//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laundry
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anbar
    {
        public string Name { get; set; }
        public Nullable<long> Some { get; set; }
        public Nullable<long> DateBuild { get; set; }
        public Nullable<long> DateExpierd { get; set; }
        public Nullable<long> DateEnter { get; set; }
        public Nullable<long> DateOut { get; set; }
        public long Id { get; set; }
    }
}
