//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnbarParent
    {
        public long Id { get; set; }
        public Nullable<long> Case { get; set; }
        public Nullable<long> Date { get; set; }
        public string Description { get; set; }
    }
}
