//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnbarProdoct
    {
        public long Id { get; set; }
        public Nullable<long> IdUnit { get; set; }
        public string Name { get; set; }
        public Nullable<long> Code { get; set; }
        public string Description { get; set; }
        public string Barcode { get; set; }
        public string RfID { get; set; }
    }
}
