//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anbar
    {
        public string Name { get; set; }
        public Nullable<long> IdProdoct { get; set; }
        public Nullable<long> IdParent { get; set; }
        public Nullable<long> Count { get; set; }
        public Nullable<long> Some { get; set; }
        public Nullable<long> Price { get; set; }
        public string Description { get; set; }
        public Nullable<long> DateBuild { get; set; }
        public Nullable<long> DateExpierd { get; set; }
        public Nullable<long> CodeRahgiri { get; set; }
        public Nullable<long> IdStore { get; set; }
        public long Id { get; set; }
    
        public virtual AnbarParent AnbarParent { get; set; }
        public virtual Store Store { get; set; }
        public virtual AnbarProdoct AnbarProdoct { get; set; }
    }
}
