//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resturant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Button
    {
        public string Name { get; set; }
        public string Text { get; set; }
        public string Price { get; set; }
        public long Id { get; set; }
        public byte[] Favorite { get; set; }
    }
}
