//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laundry
{
    using System;
    using System.Collections.Generic;
    
    public partial class Colleague
    {
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Tel { get; set; }
        public Nullable<long> DateEnter { get; set; }
        public Nullable<long> DateBirthDay { get; set; }
        public string Sex { get; set; }
        public string Address { get; set; }
        public string CardNumber { get; set; }
        public string AccountNumber { get; set; }
        public string Description { get; set; }
        public string Email { get; set; }
        public string Eshterak { get; set; }
        public long Id { get; set; }
    }
}
