//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public string Printer1 { get; set; }
        public string Printer2 { get; set; }
        public string Printer3 { get; set; }
        public string Printer4 { get; set; }
        public string Printer5 { get; set; }
        public string Printer6 { get; set; }
        public string Other { get; set; }
        public string Other2 { get; set; }
        public string Other3 { get; set; }
        public long Id { get; set; }
    }
}
